name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore: ['**.md', 'docs/**', 'LICENSE', '.gitignore', '.editorconfig']
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', 'docs/**', 'LICENSE']

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
